### ISSUE TITLE
Pair of serialization/deserialization of IDictionary doesn't work

### ISSUE THREAD

**Issue by mabakay** [deniszykov/msgpack-unity3d#1]
Make property of type Dictionary<Key, Value>, everything works great. Change it type to generic interface IDictionary<Key, Value>, works on serialization but throw exception when trying to deserialize.

**Comment by deniszykov** [comment]
fixed in 7bf3b6945ca66b3030f4092d4e47632020b0d8d0 and submitted to Unit Asset Store
Thanks for reporting issue!

**Comment by mabakay** [comment]
Thanks for such fast fix!
