### ISSUE TITLE
Guid de-serialization

### ISSUE THREAD

**Issue by Janry** [deniszykov/msgpack-unity3d#16]
Hi, I found a bug with Guid de-serialization, v.2.3.0.

            Guid before = Guid.NewGuid();
            Console.WriteLine($"before: {before}");

            MemoryStream stream = new MemoryStream();
            MsgPack.Serialize(before, stream);

            stream.Position = 0;

            Guid after = (Guid)MsgPack.Deserialize(typeof(Guid), stream);
            Console.WriteLine($"after: {after}");

before: 0672a5be-20bd-4f54-8b86-c2e391b0cc99
after: bea57206-bd20-544f-8b86-c2e391b0cc99

**Comment by Janry** [comment]
I saw that it fixed 2 months ago but there's no a new version of lib in NuGet packages. Can you up version and deploy it with the fix?

**Comment by deniszykov** [comment]
Yes, I will update package soon.

**Comment by deniszykov** [comment]
I updated [Nuget package](https://www.nuget.org/packages/GameDevWare.Serialization/2.3.1). Sorry for delay.
