### ISSUE TITLE
Exposing JsonSerializationException.ErrorCode

### ISSUE THREAD

**Issue by llint** [deniszykov/msgpack-unity3d#17]
While I'm currently relying on `JsonSerializationException.ErrorCode.UnexpectedEndOfStream` (integer value: 10) to cope with asynchronous deserialization with an intermediate `MemoryStream`, I found `JSonSerializationException.Code` is a cast from `JsonSerializationException.ErrorCode`. I have to use a hardcoded integer value (10) in my application code to check for this special condition (not a hard failure, but waiting for more data, carry on later).

It would be great to change `Code` type to `ErrorCode`, while make `ErrorCode` `public`.

**Comment by deniszykov** [comment]
Hi! ```JsonSerializationException.Code``` was intended for debug or logging purpose. I could make ```ErrorCode``` enum is public in next update.

**Comment by llint** [comment]
Thank you! And thanks for the Unity3D assets update

**Comment by deniszykov** [comment]
Hi @llint! I have updated package to version v2.4.0 and exposed JsonSerializationException.ErrorCode enum.
