### ISSUE TITLE
Unexpected value when deserializing (int)

### ISSUE THREAD

**Issue by endel** [deniszykov/msgpack-unity3d#18]
Hi @deniszykov, hope you are well!

Look, I have another discrepancy deserializing a byte array. My byte array is:

```
[130, 167, 112, 108, 97, 121, 101, 114, 115, 129, 169, 72, 74, 114, 111, 108, 67, 118, 57, 71, 131, 161, 120, 0, 161, 121, 226, 161, 122, 208, 146, 168, 109, 101, 115, 115, 97, 103, 101, 115, 144]
```

**Result in JavaScript (notepack.io)** 

```javascript
msgpack.decode(new Buffer([130, 167, 112, 108, 97, 121, 101, 114, 115, 129, 169, 72, 74, 114, 111, 108, 67, 118, 57, 71, 131, 161, 120, 0, 161, 121, 226, 161, 122, 208, 146, 168, 109, 101, 115, 115, 97, 103, 101, 115, 144]))

{ players: { HJrolCv9G: { x: 0, y: -30, z: -110 } },
  messages: [] }
```

**Result in C#**

In C#, though, the "y" value is decoded as "-2", do you have any idea why this happens? Does it have something to do with the data structure I'm de-serializing into? (IndexedDictionary<string, object>)

```csharp
var memoryStream = new MemoryStream(new byte[] { 130, 167, 112, 108, 97, 121, 101, 114, 115, 129, 169, 72, 74, 114, 111, 108, 67, 118, 57, 71, 131, 161, 120, 0, 161, 121, 226, 161, 122, 208, 146, 168, 109, 101, 115, 115, 97, 103, 101, 115, 144 });

var deserialized = MsgPack.Deserialize<IndexedDictionary<string, object>> (memoryStream);
Debug.Log(deserialized["players"]["HJrolCv9G"]["y"])
// -2
```

Here follows a screenshot, if that helps:

![screen shot 2018-03-27 at 11 20 17](https://user-images.githubusercontent.com/130494/37973816-bc318682-31b1-11e8-8ff8-8edf3bf38844.png)

Any help would be appreciated, thanks a lot, and have a great week! :)

**Comment by deniszykov** [comment]
Hi, it is very interesting bug. Probably error in NegativeFixInt de-serialization.
> Does it have something to do with the data structure I'm de-serializing into? (IndexedDictionary<string, object>)

Nop.

**Comment by deniszykov** [comment]
Also, for debug and test purpose you could use following code:
```cs
			var reader = new MsgPackReader(new MemoryStream(new byte[] { 130, 167, 112, 108, 97, 121, 101, 114, 115, 129, 169, 72, 74, 114, 111, 108, 67, 118, 57, 71, 131, 161, 120, 0, 161, 121, 226, 161, 122, 208, 146, 168, 109, 101, 115, 115, 97, 103, 101, 115, 144 }), new SerializationContext());
			var tokens = reader.DebugPrintTokens();
```

Which gives the following:

```
BeginObject
	Member[<String> players] BeginObject
		Member[<String> HJrolCv9G] BeginObject
			Member[<String> x] Number[<Byte> 0]
			Member[<String> y] Number[<SByte> -2]
			Member[<String> z] Number[<SByte> -110]
		EndOfObject
	EndOfObject
	Member[<String> messages] BeginArray
	EndOfArray
EndOfObject
```

Also I found source of the problem. It is NegativeFixInt representation. Official docs are little bit confusing about how exactly it is stored. So I looked up to another implementation of MessagePack in C# and "re-imagine" its NegativeFixInt de-serialization code. 

Here is [commit](0f6fb265cd7d655112a7c6b2be8ae2afc89c008d).

**Comment by deniszykov** [comment]
NuGet package and Unity asset will be updated soon.

**Comment by deniszykov** [comment]
Version [2.3.2](https://www.nuget.org/packages/GameDevWare.Serialization/) on NuGet.
As for Unity Asset store, it took 3-7 days to get asset published by moderators.

**Comment by endel** [comment]
Thanks a lot for fixing this so quickly, @deniszykov! Seems to be working great so far! ❤️
