### ISSUE TITLE
Issue with other Msgpack libraries

### ISSUE THREAD

**Issue by timlehr** [deniszykov/msgpack-unity3d#2]
Hey Denis,

first off: thanks a lot for your work on this library. 

However, I ran into an issue which is propably just bad thinking on my end. Here is the deal: I try to encode data in Unity, writing it with a FileStream to` Application.persistentDataPath` on a 64bit Windows machine. Afterwards I try to read the file with [u-msgpack-python](https://github.com/vsergeev/u-msgpack-python) and while the string work out fine, the `float `and `int` data ist totally wrong. Do I need to take special care of something when I do this, because it seems to me that is an encoding problem? Something about the Endian? If I do it write / read the other way around (Python -> Unity) I have the same issue. The data modified in Python is not correctly read.

Int (Unity, write): `'targetHairCount': 150, 'shaveHairCount': 270`
Int (Python, read): `'targetHairCount': -27136, 'shaveHairCount': 3585`

Float (Unity, write): `Vector3(1,2,3); Vector3(4,5,6)`
Float (Python, read): ` '{'y': 8.96831017167883e-44, 'x': 4.600602988224807e-41, 'z': 2.304855714121459e-41} {'y': 5.74868682004613e-41, 'x': 4.600743118071239e-41, 'z': 6.89663052202102e-41} `

C# code:
```
    public void WriteData<T>(T data) {
        MemoryStream stream = new MemoryStream();
        MsgPack.Serialize<T>(data, stream);
        stream.Position = 0;

        Debug.Log("Data serialized");

        using (FileStream file = new FileStream(path, FileMode.Create, System.IO.FileAccess.Write)) {
            byte[] bytes = new byte[stream.Length];
            stream.Read(bytes, 0, (int)stream.Length);
            file.Write(bytes, 0, bytes.Length);
            stream.Close();
        }
    }

    public T ReadData<T>() {
        MemoryStream stream = new MemoryStream();
        using (FileStream file = new FileStream(path, FileMode.Open, FileAccess.Read)) {
            byte[] bytes = new byte[file.Length];
            file.Read(bytes, 0, (int)file.Length);
            stream.Write(bytes, 0, (int)file.Length);
        }

        stream.Position = 0;

        return MsgPack.Deserialize<T>(stream);
    }
```

Python code:
```
import umsgpack

with open('pathtofile', 'rb') as f:
    unpacked = umsgpack.unpackb(f.read())
```

**Comment by deniszykov** [comment]
Thanks for the detailed report. It looks like I made a mistake with endianess. Message pack is big-endian by specification, but I assumed it's little-endian while implementing it. Although changes will take a little time (2 lines of code :-) ). I need to describe migration routine for those who have saved data with wrong endianess.

**Comment by timlehr** [comment]
You’re welcome. Can you provide me with a hotfix in the meantime? I’m just in the middle of development and would like to use msgpack over json for the final application.

**Comment by deniszykov** [comment]
I made necessary changes in 1b8df7861ec51a42811f2234dc364c1f86b0ec13
Try it.

**Comment by timlehr** [comment]
Thanks! 👍

**Comment by deniszykov** [comment]
BTW You can read and write directly to FileStream, bypassing the MemoryStream.

**Comment by timlehr** [comment]
I know, I just tried all the methods in case I did something wrong. :)
