### ISSUE TITLE
Vector Crash

### ISSUE THREAD

**Issue by tragicy** [deniszykov/msgpack-unity3d#20]
Define a class include Vector3, and Serialize a Dictionary of the class, the Unity Crash directly.

**Comment by tragicy** [comment]
`class MyData
{
    public int Data1;
    public string Data2;
    public Vector3 Data3;
}
public class MyClass : MonoBehaviour {

	// Use this for initialization
    string path;
    public Text text;
	void Start () {
        path = Application.persistentDataPath + "/123";
        Debug.Log(path);
        FileStream fileStream = File.Open(path, FileMode.Create);
        MyData myData = new MyData();
        myData.Data1 = 1;
        myData.Data3 = new Vector3(1,2,3);
        Dictionary<int, MyData> dic = new Dictionary<int, MyData>();
        dic.Add(1, myData);
        dic.Add(2, myData);
        dic.Add(3, myData);

        MsgPack.Serialize(dic, fileStream);
        fileStream.Flush();
        fileStream.Close(); 
	}
}`

**Comment by tragicy** [comment]
class MyData
    {
        public int Data1;
        public string Data2;
        public Vector3 Data3;
    }
    public class MyClass : MonoBehaviour {

    string path;
    public Text text;
	void Start () {
        path = Application.persistentDataPath + "/123";
        FileStream fileStream = File.Open(path, FileMode.Create);
        MyData myData = new MyData();
        myData.Data1 = 1;
        myData.Data3 = new Vector3(1,2,3);
        Dictionary<int, MyData> dic = new Dictionary<int, MyData>();
        dic.Add(1, myData);
        dic.Add(2, myData);
        dic.Add(3, myData);

        MsgPack.Serialize(dic, fileStream);
        fileStream.Flush();
        fileStream.Close(); 
	}

**Comment by deniszykov** [comment]
Hi @tragicy! Which version of Unity do you use?

**Comment by Unaidedsteak** [comment]
Hi there!

I seem to get similar symptoms of Unity crashing (with no real errors) when attempting to serialize a Vector 3

```csharp
var stream = new MemoryStream();			
Vector3 vec3 = new Vector3(1f, 2f, 3f);
Json.Serialize<Vector3>(vec3, stream);
stream.Position = 0;
```

Am I just using this incorrectly?

Unity Version: 2018.2.13f1 (64-bit)

**Comment by tragicy** [comment]
@deniszykov  Unity 2017.4.11f1 (64-bit)

**Comment by tragicy** [comment]
True, Unity 5.6.2f1 (64-bit) runs correctly, for both your and my example @Unaidedsteak .

**Comment by deniszykov** [comment]
Problem was in missing defines for recent Unity versions. I have updated code in 2165332897f5a9e449ea42730f9ca6287361de2a 
Asset in Unity Assets will be updated soon.
