### ISSUE TITLE
[Request] Support for Unity 2018.3.0f2 (Script Runtime Version .NET 4.x)

### ISSUE THREAD

**Issue by hung365dev** [deniszykov/msgpack-unity3d#21]
Hi,
When using this in Unity 2018.3.0f2 (Default of Script Runtime Version is .NET 4.x) it throw error:
DynamicMethod not found in ReflectionUtils.cs. Script Runtime Version .NET 3.5.x will be remove in the future of Unity. So please fix this !
Thanks in advanced.

**Comment by deniszykov** [comment]
Hi @dongvanhung! I will look for it. But it is strange error because DynamicMethod is a part of .NET since 3.5 and should be there in 4.x.

**Comment by hung365dev** [comment]
> Hi @dongvanhung! I will look for it. But it is strange error because DynamicMethod is a part of .NET since 3.5 and should be there in 4.x.

Yes, please support for Unity 2018.3.x. Thanks in advaced.

**Comment by deniszykov** [comment]
As I discovered, there is a full support for .NET 4.x. You probably set compatibility with .NET Standard 2 which is another beast.

**Comment by deniszykov** [comment]
As temporary solution you could take [file](https://raw.githubusercontent.com/deniszykov/msgpack-unity3d/22dfe38c073fd12eaaed3cd10ac8210f10546dc8/GameDevWare.Serialization.Unity/Assets/Plugins/GameDevWare.Serialization/Metadata/ReflectionUtils.cs) from this commit 22dfe38c073fd12eaaed3cd10ac8210f10546dc8. Until new version is released.
