### ISSUE TITLE
Decode bytes starting from offset

### ISSUE THREAD

**Issue by endel** [deniszykov/msgpack-unity3d#23]
Hi @deniszykov, I hope you are well!

Is it currently possible to decode a message starting from an offset? I have a byte array with data mixed up with MessagePack objects, and it would be great if I could decode a message starting from an offset.

As a workaround, I'm creating a "slice" of the bytes in order to decode them: https://github.com/colyseus/colyseus-unity3d/blob/b6c23dded7e1541c01252bf1970af85eb48e74c5/Assets/Plugins/Colyseus/Room.cs#L306-L309

I'd appreciate it if you can give me any hints! Cheers!

**Comment by deniszykov** [comment]
Hi @endel. 

MemoryStream has non-copying slicing constructor:
```cs
public MemoryStream(byte[] buffer, int index, int count, bool writable, bool publiclyVisible)
{
	 // ...
	_buffer = buffer;
	_origin = (_position = index);
	_length = (_capacity = index + count);
	_writable = writable;
	_exposable = publiclyVisible;
	_expandable = false;
	_isOpen = true;
}
```
pass ```buffer, offset, count, writable: false```

Also, to reduce memory traffic, you could pass re-usable working buffer to ```MsgPackReader``` [constructor](https://github.com/deniszykov/msgpack-unity3d/blob/master/src/GameDevWare.Serialization.Unity/Assets/Plugins/GameDevWare.Serialization/MessagePack/MsgPackReader.cs#L196). Reclaim it after deserialization/serialization and pass it to next  ```MsgPackReader```.

**Comment by deniszykov** [comment]
For most exteme optimization you could re-use whole ```MsgPackReader```. By calling ```MsgPackReader .Reset()``` and providing your own Stream implementation with put/reset logic.

The working algorithm will look like this:
1) take MsgPackReader and it's Stream from pool
2) put ```data``` slice into Stream
3) call MsgPackReader.ReadValue(type, false)
4) reset MsgPackReader, reset Stream
5) return MsgPackReader and Stream to pool
5) return deserialized value

**Comment by endel** [comment]
Thank you so much for the detailed info @deniszykov ❤️
