### ISSUE TITLE
'Unexpected token readed 'EndOfStream' while 'BeginObject' is expected.' ?

### ISSUE THREAD

**Issue by Orhonbey** [deniszykov/msgpack-unity3d#24]
Hi 
I am use your library first time 
 but  I get this error.
Can you help me ?
Thank you.
'Unexpected token readed 'EndOfStream' while 'BeginObject' is expected.' 
![image](https://user-images.githubusercontent.com/5496544/84550546-98565500-ad13-11ea-82db-1e3d71dec869.png)

`private T ByteConverter<T>(byte[] value)
        {
            var stream = new MemoryStream();
            stream.Write(value, 0, value.Length);
            T result = (T)MsgPack.Deserialize(typeof(T), stream);
            return result;
        }`

**Comment by deniszykov** [comment]
Hi @sunal. You need to rewind back stream after Write().
```
stream.Position = 0;
```
and better to use special non-copying constructor of MemoryStream:
```
var stream = new MemoryStream(value, 0, value.Length, writable: false);
// no rewind required
```

**Comment by Orhonbey** [comment]
Thank you . 
I tried . But this error back.
![image](https://user-images.githubusercontent.com/5496544/84565538-82c44800-ad72-11ea-86bf-1dd24706c6c6.png)

**Comment by deniszykov** [comment]
Does `T` and all deserialized types has parameter-less constructor defined? 
Example:
```
class MyClass
{
    public MyClass() { /* this is parameter-less constructor */ }
}
```
This is required for deserialization. Because deserializer need to create instances of your types.

**Comment by Orhonbey** [comment]
Thank you my problem solved .
