### ISSUE TITLE
Is float supported?

### ISSUE THREAD

**Issue by 253153** [deniszykov/msgpack-unity3d#26]
It says here:

Serialized types:

• Primitives: Boolean, Byte, Double, Int16, Int32, Int64, SBytes, Single, UInt16, UInt32, UInt64, String
• Standart Types: Decimal, DateTimeOffset, DateTime, TimeSpan, Guid, Uri, Version, DictionaryEntry
Unity3D Types: Bounds, Vector, Matrix4x4, Quaternion, Rect, Color
• Binary: Stream, byte[]
• Lists: Array, ArrayList, List[T], HashSet[T] and any other IEnumerable types with Add method
• Maps: Hashtable, Dictionary[K,V], and other IDictionary types
• Nullable types
• Enumeration
• Objects

Is float supported?
Thanks!

**Comment by deniszykov** [comment]
Yes. Two IEEE 754 floating point number types are supported:
Double - Float 64-bit
Single - Float 32-bit
