### ISSUE TITLE
Compatability with the MessagePack-CSharp library

### ISSUE THREAD

**Issue by 253153** [deniszykov/msgpack-unity3d#27]
Hi Denis,

I am writing a Unity WebGL multiplayer game. My server is in .NET and is using the MessagePack-CSharp library. My client is in Unity (WebGL) and is using your msgpack-unity3d library. 

The MessagePack-CSharp library has 2 ways to put keys into the messagepack objects: 
```

[MessagePackObject]
public class MyClass
{
    [Key(0)]
    public int Age { get; set; }
}

```
OR
```

[MessagePackObject(keyAsPropertyName: true)]
public class MyClass
{
    public int Age { get; set; }
}

```
Which way should I do it so it works with your msgpack-unity3d library? Can it be done both ways? I cannot find it in the documentation. My message pack message class definition looks like this when using your library, I am not even using getters and setters (should I be?):

```
public class MyClass
{
    public int Age;
}
```

Thank you!

**Comment by deniszykov** [comment]
Hi,
The first option:

```csharp

[MessagePackObject]
public class MyClass
{
    [Key(0)]
    public int Age { get; set; }
}
```
which writes objects as tuples, is not supported.

The second one:

```csharp

[MessagePackObject(keyAsPropertyName: true)]
public class MyClass
{
    public int Age { get; set; }
}
```

is supported and is the only option for object serialization.
It should work with both properties and fields from my side.

**Comment by deniszykov** [comment]
My library uses the rules of Data Contract serialization from the older .NET serializers. These rules are described in the README file.

**Comment by 253153** [comment]
Thank you very much for your prompt response! Do we need getters and setters? If they are present in one end and not present in the other is it ok? Do they affect anything?

**Comment by deniszykov** [comment]
> Do they affect anything?

In this library - no.

**Comment by 253153** [comment]
And no constructor required either? Or any [] tags or anything like this?

**Comment by deniszykov** [comment]
Empty constructor is required. It is created by default if no constructors are defined on type.
