### ISSUE TITLE
MsgPackReader.cs ReadBytes(long bytesRequired, bool forceNewBuffer = false) Problem

### ISSUE THREAD

**Issue by sadradelir** [deniszykov/msgpack-unity3d#6]
Hi, I have a serialized class from java msgpack library that have byte[] field, and I get array out of bound exception in :
MsgPack.cs line 536  :
                        Buffer.BlockCopy(this.buffer, this.bufferOffset, bytes, 0, this.bufferAvailable);

because required bytes are 589 and destination byte array is byte[589] but bufferAvailable ( passed as count ) is 1308 ! 

would you help me to fix this issue ?

**Comment by deniszykov** [comment]
Thanks for detailed report. 
Fixed in 135d160e4bb73a4aaaf1be5a52bf8f113011be29 commit.

**Comment by sadradelir** [comment]
thanks for fast reply and fix, I merge MsgPackReaderClass.cs with my own one and now I get 
   JsonSerializationException: Unexpected end of stream 
for one of my classes that haven't any problem before this fix, I read source code two times and i cant realize why I get this.

**Comment by deniszykov** [comment]
Can you provide data in Base64 for testing. This will help to fix this issue faster.

**Comment by deniszykov** [comment]
I have found 'unexpected EndOfStream' bug and fixed it in 97e307bf8a86bc0c57beb85912f594b1d58f493d. If you still have an issue, please send test data.

**Comment by sadradelir** [comment]
It seems this issue is fixed by the commit, but I am going to test it continuously, if get any error I will post it. thank you.
