### ISSUE TITLE
Can not JSON serialize an IndexedDictionary

### ISSUE THREAD

**Issue by ppawlak** [deniszykov/msgpack-unity3d#7]
Hello,

Using your provided _IndexedDictionary_ type, Json serialize does not work. 
This little code snippet fails :
		
		
		var dict = new IndexedDictionary<string, int> ();
		dict ["foo"] = 42;

		var stream = new MemoryStream();
		Json.Serialize(dict, stream);

The error is :

	InvalidCastException: Cannot cast from source type to destination type.

It happens in DictionarySerializer.cs, line 176 when casting the value to an _IDictionary_.

It would be convenient to support serializing for this type. In my real project I have an _IndexedDictionary_ object from deserializing an msgpack message I want to convert to Json.

**Comment by deniszykov** [comment]
I have fixed it in this b9c1db973085bd1c1199aaf1c018024f61f8c9e6 commit. Thanks for report.

**Comment by ppawlak** [comment]
I have integrated your changes in my project and tested them. It works perfectly.
Thank you very much for fixing this issue so quickly !
